defaults:
  - _self_ # default.yaml itself
  - architecture: base

base_lr: 0.0005
warmup_lr: 0.0000005
warmup_epochs: 1
total_steps: 1000
batch_size: 32
epochs: 2
patience: 4
clip_grad: 0.5
temperature: 0.5
log_interval: 10
save_top_k: 3
run_name: "hydra-test-1"
offline: True
